name: Sanity
description: "Spruce up your server with a little bit of this, and a little bit of that!"
version: 0.0.1
authors: [redraskal, Hunkboy]
main: me.redraskal.sanity.Main

commands:
  sanity:
    description: "Just a bit of information about this project."